// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDPGfjAmjTJzG3GZxM6NKCaCyXtbtOrPk',
    appId: '1:732404273820:web:235c4d4152ed54ede5d359',
    messagingSenderId: '732404273820',
    projectId: 'calsob-shop-229f7',
    authDomain: 'calsob-shop-229f7.firebaseapp.com',
    storageBucket: 'calsob-shop-229f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjmQ_r6YqlDCg2tX48VrN-6F_rSUXJQCM',
    appId: '1:732404273820:android:65167c74f6d44de6e5d359',
    messagingSenderId: '732404273820',
    projectId: 'calsob-shop-229f7',
    storageBucket: 'calsob-shop-229f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOeQpwGL3n6la2PAUsi6JPu1atuGd2jcs',
    appId: '1:732404273820:ios:3d5107d4a5c75408e5d359',
    messagingSenderId: '732404273820',
    projectId: 'calsob-shop-229f7',
    storageBucket: 'calsob-shop-229f7.appspot.com',
    iosBundleId: 'com.example.noti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOeQpwGL3n6la2PAUsi6JPu1atuGd2jcs',
    appId: '1:732404273820:ios:a29372ae95795a4ae5d359',
    messagingSenderId: '732404273820',
    projectId: 'calsob-shop-229f7',
    storageBucket: 'calsob-shop-229f7.appspot.com',
    iosBundleId: 'com.example.noti.RunnerTests',
  );
}
